spring.application.name=autenticacion-service
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400
application.security.jwt.refresh-token.expiration=604800

spring.r2dbc.url=r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.pool.enabled=true
spring.show-sql=false
debug=true

aws.region=${AWS_REGION}
aws.sqs.queue-url=${AWS_SQS_QUEUE_URL}

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
