spring.application.name=eventslambda
spring.cloud.function.definition=handleSqsMessages

aws.region=${AWS_REGION}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME}
aws.sqs.queue-url=${SQS_QUEUE_URL}

aws.dynamodb.endpoint=${DYNAMODB_ENDPOINT}

spring.main.web-application-type=none

logging.level.software.amazon.awssdk=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.root=INFO
MAIN_CLASS=com.awscore.eventslambda.MyLambdaFunctionHandler

spring.profiles.active=pdn
